spring.application.name=EcomProductService

#FakseStore Configuration
fakeStore.api.url=https://fakestoreapi.com
fakeStore.api.path.product=/products
fakeStore.api.path.category=/category


#DB Config
spring.datasource.url=jdbc:mysql://localhost:3306/ECom
spring.datasource.username=root
spring.datasource.password=Vikas@1998
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update